LEX = lex
YACC = yacc -d

CC = gcc

parser: y.tab.o lex.yy.o
	$(CC) -o parser y.tab.o lex.yy.o 
	./parser < cs315_team18_test.txt


lex.yy.o: lex.yy.c y.tab.h
lex.yy.o y.tab.o: y.tab.c


y.tab.c y.tab.h: cs315_team18_yacc.y
	$(YACC) -v cs315_team18_yacc.y


lex.yy.c: cs315_team18_lex.l
	$(LEX) cs315_team18_lex.l
